### PR TITLE
I also solved the installation and upgrade tools for Linux

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by TheFitzZZ** [comment]
Can confirm the code works (thx @BDisp for sharing!)

**Comment by bugb** [comment]
@BDisp  It works pretty well, thank you so much for sharing!

**Comment by BDisp** [comment]
> **Problem with Vmware 15.5**: I can not find `mac os` option when selecting os type. The script from BDisp works but it does not bring `mac os` option.

@bugb thanks for your reply. Here is a print screen that prove that 'mac os' option is displaying on linux OS. On VMware 14 version I'm not aware if it is working or not because I didn't tested it yet. I'll check your script too.
macOS_linux

**Comment by BDisp** [comment]
@bugb here is a print screen with the 'mac os' option using VMware Workstation 14 on linux OS. Maybe you were referring to the versions of mac that come in the combo box. If so, VMware 14 really only exists up to macOS 10.14 and VMware 15.5 only up to macOS 10.16. If you were not referring to any of this can you clarify what is at stake please? Thanks.

macOS_vmware14_linux

**Comment by Vthyarilops** [comment]
Just a note, in lnx-install.sh "python gettools.py" has to be changed to "python3 gettools.py" to download the tools, with python 2.7.15+ I get this error https://pastebin.com/GYMmGMLe

**Comment by BDisp** [comment]
@Vthyarilops with the below link the version issue was solved. The code only was compatible with python 3. Now is python 2.7 compatible too.
https://github.com/BDisp/unlocker/releases/tag/3.0.3

**Comment by bugb** [comment]
@BDisp I do not know, it was weird in my case, btw I am not using VMware anymore, I just switched to Virtual box, it is easy to hack. But I think your script works...

**Comment by BDisp** [comment]
@bugb with me was the other way around. Some time ago I used to use Virtual Box until an upgrade from macOS Sierra crashed and after trying the same image on VMware started working again and from there I didn't want to switch to Virtual Box anymore.

**Comment by JohnBergman** [comment]
After upgrading from 15.1 to 15.5, I dont have the macos in the list, but oddly have macos 10.12 in the dropdown with no radio buttons selected.  I upgraded to 15.5 today.

image

**Comment by BDisp** [comment]
Which unlocker version did you run?

**Comment by JohnBergman** [comment]
3.0.2 from the releases

**Comment by BDisp** [comment]
@DrDonk hasn't updated their release yet. You have to use version 3.0.3. In the comments has the link. https://github.com/BDisp/unlocker/releases/tag/3.0.3

**Comment by BDisp** [comment]
I'll submit again in a new branch

**Pull request closed without merging**
