### PR TITLE
Fix remote file not found error

### PR DESCRIPTION
**Pull request by paolo-projects**
Last published version doesn't ship with darwin tools so in case of error fall back to the latest version that has them
Also needs the main bash script to be updated to use this python script in place of the exe

### CODE REVIEW

**Comment by hdei28** [comment]
Hello, I have a problem with the script:

Relocation modified at: 0xb11c8
Relocation modified at: 0xb11e0
Relocation modified at: 0xb11f8
Relocation modified at: 0xb1210
GOS Patching: /usr/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so
GOS Patched: /usr/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so
Getting VMware Tools...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.5.0/14634996/packages/com.vmware.fusion.tools.darwin.zip.tar
Traceback (most recent call last):
  File "gettools.py", line 159, in <module>
    main()
  File "gettools.py", line 112, in main
    tar = tarfile.open(convertpath(dest + '/tools/com.vmware.fusion.tools.darwin.zip.tar'), 'r')
  File "/usr/lib/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully


How to???

**Comment by hdei28** [comment]
Capture d’écran_2019-09-22_19-22-30

**Comment by paolo-projects** [comment]
I guess you're using an old python version. Install python 3.7 and set it as default, or change the command in the linux script to "python3.7 gettools.py" 

I guess previous versions don't use exception handling

**Comment by hdei28** [comment]
In my synaptic manager, I have both versions install: python 2 and python 3 which were installed by default with debian 10. The script worked before it stopped working.
I do not know how to put python 3 by default or find the solution. I downloaded the script at this address: "https://github.com/DrDonk/unlocker" but I have the same problem. How to do?

**Comment by paolo-projects** [comment]
This thread is a pull request, in other words a discussion topic where I propose the owner of the application a fix for something that is not working in the program. The owner didn't reply yet but you can go to my forked repository to get the working script. clone this repository or download it: https://github.com/paolo-projects/unlocker

Also as I have said before I tested this script on python 3.7 so ideally you should use the same version to run the script. You can force the script to run python 3.7 by editing *lnx-install.sh* file and changing the word **python** with **python3** or **python3.7** to be more specific.

**Comment by Goserizz** [comment]
I have the same issue too. I think the problem is from the file sharing server. The link where tools are downloaded from shows "File not found".

**Comment by hdei28** [comment]
OK, I have download this: https://github.com/paolo-projects/unlocker and modified the lnx-install.sh but i have this error: 

Capture d’écran_2019-09-23_09-22-02
Capture d’écran_2019-09-23_09-17-00

**Comment by paolo-projects** [comment]
No, you have to make the change to the command that is 2 lines below: "python gettools.py" to "python3 gettools.py" or python3.7
And cd to the script folder before executing it

**Comment by Goserizz** [comment]
> No, you have to make the change to the command that is 2 lines below: **python gettools.py** to **python3 gettools.py** or python3.7
> And _cd to the script folder before executing it
That works, thx.

**Comment by Goserizz** [comment]
> No, you have to make the change to the command that is 2 lines below: **python gettools.py** to **python3 gettools.py** or python3.7
> And _cd to the script folder before executing it_

That works, thx!

**Comment by hdei28** [comment]
Now, I have this message: 

Capture d’écran_2019-09-23_09-22-02
Capture d’écran_2019-09-23_14-15-31

**Comment by daffinm** [comment]
Big thanks @paolo-projects. This worked perfectly - I am up and running again. 

Does anyone know why the packages folder is missing from the [11.5.0 release](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.5.0/)?

And does anyone know why I always need to reinstall both VMWare Player and then run unlocker each time my OS updates? (I am running Ubuntu 18.04 but this was true on 16.04 too.)

**Comment by paolo-projects** [comment]
> Big thanks @paolo-projects. This worked perfectly - I am up and running again.
> 
> Does anyone know why the packages folder is missing from the [11.5.0 release](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.5.0/)?
> 
> And does anyone know why I always need to reinstall both VMWare Player and then run unlocker each time my OS updates? (I am running Ubuntu 18.04 but this was true on 16.04 too.)

Thank you for your appreciation! I hope the owner merges my fix but until then I'm glad it helped someone.

The reason why the packages folder is missing is probably because they didn't create ad updated version yet, but I'm only guessing. Until then, the previous version still works so there's no issue for us lol.

**Comment by daffinm** [comment]
> Until then, the previous version still works so there's no issue for us lol.
Indeed. If it ain't broke... find it and use it. (So glad I didn't have to hack this myself. Last thing I had time for today :)

**Comment by SuperNoa** [comment]
> 
> 
> OK, I have download this: https://github.com/paolo-projects/unlocker and modified the lnx-install.sh but i have this error:
> 
> Capture d’écran_2019-09-23_09-22-02
> Capture d’écran_2019-09-23_09-17-00

I have the same issue

**Comment by daffinm** [comment]
@SuperNoa How are you running unlocker on windows and what error are you seeing? (Can't be exactly the same issue because the windows version uses a different set of top-level executables.)

**Comment by paolo-projects** [comment]
> > OK, I have download this: https://github.com/paolo-projects/unlocker and modified the lnx-install.sh but i have this error:
> > Capture d’écran_2019-09-23_09-22-02
> > Capture d’écran_2019-09-23_09-17-00
> 
> I have the same issue on Windows

I initially made the patch for my windows machine so it works for sure. Make sure you have python 3.7 installed in your PATH, clone my fork and double click win-install.cmd

**Comment by DannyKielman** [comment]
First of all thanks for your efforts so far, it is really helpful! I can get the scripts to fully run on Ubuntu and Windows. I can see 'Finished!' on both install and update-tools scripts. However VMware Player is still not giving me the option to select Mac OS X as the operating system. Are there still some lines being skipped in the script maybe?

image

**Comment by paolo-projects** [comment]
> First of all thanks for your efforts so far, it is really helpful! I can get the scripts to fully run on Ubuntu and Windows. I can see 'Finished!' on both install and update-tools scripts. However VMware Player is still not giving me the option to select Mac OS X as the operating system. Are there still some lines being skipped in the script maybe?
> 
> image

No, it happened to me too. Try a previous version of VMware Player (don't know which one) or get VMware Workstation.

**Comment by hdei28** [comment]
Do you have a fix for my error message to me? Thank you

**Comment by DannyKielman** [comment]
> Do you have a fix for my error message to me? Thank you

I think you should keep unlocker.py running on python2 (just python) and gettools.py can be on python3. That non byte literals error also doesn't happen with python2
https://stackoverflow.com/questions/38326297/byte-string-spanning-more-than-one-line

**Comment by SuperNoa** [comment]
> 
> 
> @SuperNoa How are you running unlocker on windows and what error are you seeing? (Can't be exactly the same issue because the windows version uses a different set of top-level executables.) Or do you mean that you are having the same original issue:
> 
> > [Last published version](http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.5.0/14634996/) doesn't ship with darwin tools so in case of error fall back to the latest version that has them
> 
> This patch is for the linux version only AFAIKS.

Cattura

**Comment by tieubao81** [comment]
> 
> 
> > First of all thanks for your efforts so far, it is really helpful! I can get the scripts to fully run on Ubuntu and Windows. I can see 'Finished!' on both install and update-tools scripts. However VMware Player is still not giving me the option to select Mac OS X as the operating system. Are there still some lines being skipped in the script maybe?
> > image
> 
> No, it happened to me too. Try a previous version of VMware Player (don't know which one) or get VMware Workstation.

I'm running Workstation Pro 15.5... your revisions downloaded the correct tool files and patches, but vmware 15.5 still doesn't give me an option for macOS... can I install it as Other 64 bit?

image

**Comment by marlonfrank30** [comment]
all was well until today where basically vmware workstation v15 decided to update my box to 15.5.0 build-14665864. any plans to cover this version too?

**Comment by byronwai** [comment]
@marlonfrank30 
as mentioned in the earliest thread, darwin tool does not comes with VMware fusion. However, it will be possible to use the darwin tool released on VMware fusion 11.1.

**Comment by BDisp** [comment]
Mojave display scaling is not working with the previous tool. Must follow Protégé instructions in https://www.insanelymac.com/forum/topic/335757-macos-unlocker-v30-for-vmware-workstation/?page=3.

**Comment by paolo-projects** [comment]
I will make a summary of all the fixes to common errors I've come across and I've been able to solve

* **Could not download remote tools from server**
  
  Get Python 3.7 and the updated tool here: [https://github.com/paolo-projects/unlocker](https://github.com/paolo-projects/unlocker)
* **Cannot mix byte and non byte literals**
  
  Refer to this thread: [https://github.com/DrDonk/unlocker/pull/48](https://github.com/DrDonk/unlocker/pull/48) and apply his patch to the script. If you're on windows, just use the supplied unlocker.exe (in other words make sure you didn't change the *unlocker.exe* line inside the *win-install.cmd* file) and it should work fine.
  
* **MacOS X not shown in VMware guest types after patch**

  Try a previous version, the Workstation edition if you're able to, or a previous version of the Workstation edition
  
* **Screen not resizing after installing tools**

  Couldn't find a fix for it. After you install the tools you'll be able to set the desired resolution from terminal using the provided application.
  
  It can be found in the guest under */Library/Application Support/VMware Tools/*
  
  The application name is **vmware-resolutionSet**
  
* **CPU error using AMD CPUs (due to the lack of vt-x)**

  Refer to this guide: [https://www.intoguide.com/how-to-install-macos-mojave-on-vmware-with-amd-processors/](https://www.intoguide.com/how-to-install-macos-mojave-on-vmware-with-amd-processors/)

**Comment by TomasLinhart** [comment]
Somebody managed to fix the script, the update is available at https://www.insanelymac.com/forum/topic/335757-macos-unlocker-v30-for-vmware-workstation/?page=3

**Comment by BDisp** [comment]
@paolo-projects the unlocker.py is really working fine posted by @mkitchin in the site I’d mentioned above. Install Pyinstaller to compile to exe using the win-build.cmd file. To test with the py files use the win-test-install.cmd and not the win-install.cmd file. I already had fixed the "Cannot mix byte and non byte literals" error by adding the b character but I wasn't be able to fix to make macOS show up as an option in VMware 15.5 and @mkitchin did it. Add his solution to your github :)

**Comment by mk-mrityunjay** [comment]
I have also tried in windows after changing win-install.cmd like below:

echo Patching...
python3.7 ./unlocker.py
::unlocker.exe

But received error message in unlocker.py as :




*Patching...  File "./unlocker.py", line 305    darwin
=b'\x10\x00\x00\x00\x10\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00' \
     ^SyntaxError: cannot mix bytes and nonbytes literals*
[image: Capture.PNG]

*Regards,*
*Mrityunjay Kumar*

**Comment by dayfan0810** [comment]
Getting VMware Tools...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.5.0/14634996/packages/com.vmware.fusion.tools.darwin.zip.tar


But this is not Archived in the site, 11.5.0/14634996/ has no packages

**Comment by flyinghuman** [comment]
i updated the vmware tools path and also the binarys. works for 15.5 if you manually create the vmx file (MacOS is not selectable in New Virtual Machine Wizard but if you use a existing MacOS vmx File you will be able to edit and boot it.) i attached a sample vmx file for that.

https://github.com/flyinghuman/unlocker

**Comment by BDisp** [comment]
@mk-mrityunjay that code have to be changed to:
darwin = re.compile(
             	b'\x10\x00\x00\x00[\x10|\x20]\x00\x00\x00[\x01|\x02]\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')

Here is the complete code https://pastebin.com/7atm6DfU

@flyinghuman the above link code works fine, try it.

I already confirmed that the iso files only start appear in the "com.vmware.fusion.zip\payload\VMware Fusion.app\Contents\Library\isoimages" beginning from the 11.5.0 version. So, the gettools script have to be change to get the tools from the packages folder and if it's not found then it has to get in the core folder. That is not easy but it's less difficult than the unlocker script for sure :)

**Comment by paolo-projects** [comment]
> @paolo-projects the unlocker.py is really working fine posted by @mkitchin in the site I’d mentioned above. Install Pyinstaller to compile to exe using the win-build.cmd file. To test with the py files use the win-test-install.cmd and not the win-install.cmd file. I already had fixed the "Cannot mix byte and non byte literals" error by adding the b character but I wasn't be able to fix to make macOS show up as an option in VMware 15.5 and @mkitchin did it. Add his solution to your github :)

I'll give it a look :)

> @mk-mrityunjay that code have to be changed to:
> darwin = re.compile(
> b'\x10\x00\x00\x00[\x10|\x20]\x00\x00\x00[\x01|\x02]\x00\x00\x00\x00\x00\x00\x00'
> b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
> 
> Here is the complete code https://pastebin.com/7atm6DfU
> 
> @flyinghuman the above link code works fine, try it.
> 
> I already confirmed that the iso files only start appear in the "com.vmware.fusion.zip\payload\VMware Fusion.app\Contents\Library\isoimages" beginning from the 11.5.0 version. So, the gettools script have to be change to get the tools from the packages folder and if it's not found then it has to get in the core folder. That is not easy but it's less difficult than the unlocker script for sure :)

I'll give a look at this too. I'm not so good at python programming I'd rather make a C++ app but I know python is the best choice here for the multi platform solution. A complication is that the core tar is 500mb+ size thus requiring a download, extraction and unzipping of a large file. I guess the choice it's either this or using a previous version

**Comment by BDisp** [comment]
Yes, the size of the tar file it's a complication. The problem with the previous version is that they possible stay out of date and without new features. Another solution is to write a readme.txt with instructions to how to get the tools and where to paste. I'm almost pretty sure it will always be that way that VMware will make the tools available in the future.

**Comment by paolo-projects** [comment]
I updated my fork with the fixes you pointed out, though I just tested the gettools part as I don't have vmware on this pc. Could someone please test if it works as intended with last version of vmware? --> [https://github.com/paolo-projects/unlocker](https://github.com/paolo-projects/unlocker)

**Comment by ebonato** [comment]
Just tested with Workstation 15.5.0 build-14665864 (Latest).
image

image


Tks @paolo-projects, you rock!!

**Comment by paolo-projects** [comment]
Thank you for your appreciation. Most of the credits go to @mkitchin for the updated patch script and @BDisp for pointing out the latest tools location.

**Comment by BDisp** [comment]
@paolo-projects congratulations for your great job. It's working very well. The iso.sig files don't exist anymore in the core folder. I think they are used to check the iso images signature , but probably no needed anymore.

**Comment by alexnt85** [comment]
I can't make it work on workstation 15.5
It runs fine on 15.1
This is my .mvx
`.encoding = "windows-1252"
config.version = "8"
virtualHW.version = "10"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsilogic"
memsize = "4096"
scsi0:0.present = "TRUE"
scsi0:0.fileName = "OS X Mavericks.vmdk"
scsi0:1.present = "TRUE"
scsi0:1.deviceType = "cdrom-raw"
ethernet0.virtualDev = "e1000e"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.addressType = "generated"
usb.present = "TRUE"
ehci.present = "TRUE"
ehci.pciSlotNumber = "34"
sound.present = "TRUE"
sound.virtualDev = "hdaudio"
sound.fileName = "-1"
sound.autodetect = "TRUE"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
smc.present = "TRUE"
hpet0.present = "TRUE"
ich7m.present = "TRUE"
usb.vbluetooth.startConnected = "TRUE"
board-id.reflectHost = "TRUE"
firmware = "efi"
displayName = "OS X Mojave"
guestOS = "darwin18-64"
nvram = "OS X Mavericks.nvram"
virtualHW.productCompatibility = "hosted"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.suspend = "soft"
powerType.reset = "soft"
extendedConfigFile = "OS X Mavericks.vmxf"
uuid.bios = "56 4d aa 1c f0 e9 cb 50-49 2b 61 a9 61 35 1f c6"
uuid.location = "56 4d aa 1c f0 e9 cb 50-49 2b 61 a9 61 35 1f c6"
replay.supported = "FALSE"
replay.filename = ""
scsi0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "16"
usb.pciSlotNumber = "32"
annotation = "     OS X Mavericks 10.9 VMware Image|0D|0A-------------------------------------------|0D|0A             Courtesy of ZackehSoul|0D|0A-------------------------------------------|0D|0A|0D|0A- For instructions visit the link in the downloaded folder.|0D|0A- Based on Mavericks 10.9 GM as of the day of its release.|0D|0A- If you need to contact me quickly, you can find me here; http://q.gs/wQNX|0D|0A- You can also email me at zackehsoul@hotmail.co.uk, or find me on http://souldevteam.net."
ethernet0.pciSlotNumber = "160"
sound.pciSlotNumber = "33"
vmci0.pciSlotNumber = "35"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "806628803"
vmotion.checkpointFBSize = "134217728"
cleanShutdown = "TRUE"
softPowerOff = "FALSE"
usb:1.speed = "2"
usb:1.present = "TRUE"
usb:1.deviceType = "hub"
usb:1.port = "1"
usb:1.parent = "-1"
toolsInstallManager.updateCounter = "259"
tools.remindInstall = "FALSE"
numvcpus = "4"
cpuid.coresPerSocket = "4"
numa.autosize.vcpu.maxPerVirtualNode = "4"
numa.autosize.cookie = "40001"
migrate.hostlog = ".\OS X Mavericks-d3200aea.hlog"
monitor.phys_bits_used = "40"
scsi0:1.startConnected = "FALSE"
gui.lastPoweredViewMode = "fullscreen"
scsi0:1.fileName = "auto detect"
tools.syncTime = "FALSE"
toolsInstallManager.lastInstallError = "21004"
svga.maxWidth = "1920"
svga.maxHeight = "1080"
svga.vramSize = "134217728"
checkpoint.vmState = ""
isolation.tools.hgfs.disable = "FALSE"
sharedFolder0.present = "true"
sharedFolder0.enabled = "true"
sharedFolder0.readAccess = "true"
sharedFolder0.writeAccess = "true"
sharedFolder0.hostPath = "D:\xxxx"
sharedFolder0.guestName = "xxxx"
sharedFolder0.expiration = "never"
sharedFolder.maxNum = "1"
gui.exitOnCLIHLT = "TRUE"
workingDir = "."
ethernet1.pciSlotNumber = "-1"
ethernet1.addressType = "generated"
ethernet1.virtualDev = "e1000e"
ethernet1.generatedAddressOffset = "10"
ethernet0.present = "TRUE"
ethernet0.generatedAddress = "00:0C:29:35:1F:C6"
acpi.smbiosVersion2.7 = "FALSE"
vmotion.checkpointSVGAPrimarySize = "268435456"
smc.version = “0”
cpuid.0.eax = "0000:0000:0000:0000:0000:0000:0000:1011"
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
cpuid.1.eax = "0000:0000:0000:0001:0000:0110:0111:0001"
cpuid.1.ebx = "0000:0010:0000:0001:0000:1000:0000:0000"
cpuid.1.ecx = "1000:0010:1001:1000:0010:0010:0000:0011"
cpuid.1.edx = "0000:1111:1010:1011:1111:1011:1111:1111"
featureCompat.enable = "FALSE"
vmxnet3.serialNumberV2 = "FALSE"
gui.applyHostDisplayScalingToGuest = "FALSE"
gui.stretchGuestMode = "fullfill"
gui.enableStretchGuest = "FALSE"
scsi0:1.autodetect = "TRUE"
floppy0.present = "FALSE"
usb:0.present = "TRUE"
usb:0.deviceType = "hid"
usb:0.port = "0"
usb:0.parent = "-1"
`

**Comment by alexnt85** [comment]
I cant run it on 15.5 version but it is ok on15.1
[https://www.dropbox.com/s/9ca7shd4qfwcjiy/OS%20X%20Mavericks.vmx?dl=0](url)

**Comment by alexnt85** [comment]
I can't make it run on 15.5 but on 15.1 runs fine
I even tried with flyinghuman 's unlocker
This is my vmx:
[https://pastebin.com/KsDSPDWd](url)

**Comment by BDisp** [comment]
I already tested with the VMware Player and VMware Workstation Pro and both work well with the @paolo-projects changes. You must install from the https://github.com/paolo-projects/unlocker 's version. Don't forget that you must run as admin to successfully install unlocker. If still there are errors you must explain which operation system are used. @alexnt85 maybe you have some misconfiguration in your vmx file.

**Comment by alexnt85** [comment]
> maybe you have some misconfiguration in your vmx file.

there can't be misconfiguration as 15.1 runs the vm fine.

**Comment by hdei28** [comment]
Hi,

Now, I have this error message:

c1
c2

**Comment by mkitchingh** [comment]
@paolo-projects  I just found this comment thread and realize I'm (mkitchin) getting credit for several fixes. All I really did was take several fixes, combine them, and then compile to an exe where needed. I then put it on a public share. I'm very interested in this project staying current. I assumed Donk would update his code, but it doesn't seem to have happened. He has indicated he is aware of the issue. I'm happy to help in any way I can. I'm not much of a Python coder and I also have no clue on exactly how the unlocker portion of the script does what it does. I'm also have no idea where the user serezha at https://www.insanelymac.com/forum/topic/335757-macos-unlocker-v30-for-vmware-workstation/?page=2 with a total of 4 posts came from and was able to create the patch that resolved the main issue (not the tools issue) with 15.5. His compiled version triggered a virus alert in Windows Defender. I recompiled the new exe and the alert went away.

**Comment by quericy** [comment]
> I updated my fork with the fixes you pointed out, though I just tested the gettools part as I don't have vmware on this pc. Could someone please test if it works as intended with last version of vmware? --> https://github.com/paolo-projects/unlocker
> 
> **Edit:** I just tested it with VMware Player 15.5 and it works fine. In addition to @mkitchin patched unlocker.py now it also checks for the tools in the packages folder and if not found it gets them from _com.vmware.fusion.zip_ as @BDisp pointed out.

it works! Thanks~

**Comment by KnockKnockP** [comment]
Hi, I get "xcopy is not recognized as an internal or external command" error.

I also "PermissionError: [Errno 13] Permission denied: 'D:\\vmware\\vmwarebase.dll'" error as well.

**Comment by sobakasu** [comment]
Windows defender complains that unlocker.exe has Trojan:Win32/Tiggre!plock

**Comment by alexnt85** [comment]
Has any one tested on ryzen 3xxx and vmwre 15.5?

**Comment by fatso83** [comment]
@paolo-projects Any idea why your executables get flagged as trojans? .... The original does not.

**Comment by VladislavAntonyuk** [comment]
@fatso83 my windows defender and eset are no mark this file as vulnerable. it is probably because this exe downloads file without user permission using http

**Comment by BDisp** [comment]
Get it from my fork at https://github.com/BDisp/unlocker and try it

**Comment by d-j-a** [comment]
I'm not seeing Mac as an OS option with 15.5 (1466) Vmware. It looks like vmwarebase.dll patches ok from the onscreen logging, is there another file that might be failing the patch script?

**Comment by BDisp** [comment]
@d-j-a I got a little confused. It's worked but they didn't work either? What you mean about that? Is virus still detected, although they are a false positive?

**Comment by d-j-a** [comment]
Sorry. I never had any issue with AV- my problem was that the patch didn't fully work and Apple was not available as a OS to select when setting up the VM.  I first tried using one of the releases you had listed, that didn't work. Downloading (clone) worked however.

**Comment by paolo-projects** [comment]
> @paolo-projects Any idea why your executables get flagged as trojans? .... The original does not.

I have no clue... I just compiled the .exe files through the included *win-build.cmd* script

> I think the confusion people have with this not working, is that they expect the releases to be under ... RELEASES. Not that surprising, perhaps :) Would you mind tagging the commits so that you get auto-generated releases?

Actually I've only seen the opposite happen, with people cloning the repo instead of going into the releases section. Anyways I just created a release

**Comment by mkitchingh** [comment]
> I have no clue... I just compiled the .exe files through the included _win-build.cmd_ script

I hadn't even noticed that script, and I had been compiling them manually. When I compile them on my Win 10 fully updated machine with the latest Python and latest PyInstaller, the exe files do not generate any virus warnings. I'm not sure what the difference is.

**Comment by alexnt85** [comment]
All of you people that made it work with workstation 15.5 you have intel platforms?

**Comment by paolo-projects** [comment]
> > I have no clue... I just compiled the .exe files through the included _win-build.cmd_ script
> 
> I hadn't even noticed that script, and I had been compiling them manually. When I compile them on my Win 10 fully updated machine with the latest Python and latest PyInstaller, the exe files do not generate any virus warnings. I'm not sure what the difference is.

When I built it on my second computer it didn't trigger any AV alert. Now I just cloned the repo on my first PC and a defender notification popped up. I guess some bad guy compiled a virus with it and now, since the compiled exe is probably just a python exe packed with libs and the script as a resource, every program gets identified as a threat because the signatures are very close. It's just a wild guess though.

**Comment by BDisp** [comment]
@paolo-projects and @mkitchingh, I use VS 2019 for developing with the integrated Python and realized that the compiled exe not generate any virus warnings. However, I did not want to advance because the laurels are for you both and I was waiting for @paolo-projects release and merge with his fork :)

**Comment by alexnt85** [comment]
> I tested it on both. AMD Ryzen gave me some headaches.
How did you manage to work?

**Comment by paolo-projects** [comment]
> > I tested it on both. AMD Ryzen gave me some headaches.
> 
> How did you manage to work?
> 
> I m not trying to install mac os now. I use an existing installation(vmdk)

I posted a Q&A a while ago in this thread. You'll find a link to an article that helped me solve the issues. Otherwise, if you don't specify what error you're getting I can't help...

**Comment by mkitchingh** [comment]
> @paolo-projects and @mkitchingh, I use VS 2019 for developing with the integrated Python and realized that the compiled exe not generate any virus warnings. However, I did not want to advance because the laurels are for you both and I was waiting for @paolo-projects release and merge with his fork :)

It seems like they never alert on the machine they were compiled on. Just for testing, see if the version I compiled a few months ago is detected as a virus for you: http://www.mediafire.com/file/w4khcmcu7hqo1a7/MK-unlocker.zip/file
I support a project where a lot of users use Unlocker. I would love to be able to get rid of the virus alerts somehow.

**Comment by paolo-projects** [comment]
> @paolo-projects and @mkitchingh, I use VS 2019 for developing with the integrated Python and realized that the compiled exe not generate any virus warnings. However, I did not want to advance because the laurels are for you both and I was waiting for @paolo-projects release and merge with his fork :)

Didn't know VS2019 compiles python code... wow! There's some spare laurels for you too! You can also create a pull request with your compiled fork I'll merge it

**Comment by alexnt85** [comment]
> 
> 
> > > I tested it on both. AMD Ryzen gave me some headaches.
> > 
> > 
> > How did you manage to work?
> > I m not trying to install mac os now. I use an existing installation(vmdk)
> 
> I posted a Q&A a while ago in this thread. You'll find a link to an article that helped me solve the issues. Otherwise, if you don't specify what error you're getting I can't help...

I get that the virtual machine failed to start.

The workaround below only works for version 15
`smc.version = "0"
cpuid.0.eax = "0000:0000:0000:0000:0000:0000:0000:1011"
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
cpuid.1.eax = "0000:0000:0000:0001:0000:0110:0111:0001"
cpuid.1.ebx = "0000:0010:0000:0001:0000:1000:0000:0000"
cpuid.1.ecx = "1000:0010:1001:1000:0010:0010:0000:0011"
cpuid.1.edx = "0000:1111:1010:1011:1111:1011:1111:1111"
featureCompat.enable = "FALSE"`

**Comment by BDisp** [comment]
@mkitchingh I just tested and no virus was detected

**Comment by mkitchingh** [comment]
> @mkitchingh I just tested and no virus was detected

Thanks. I've had 1100+ downloads on that, and 0 people report a virus detection. I have no idea why it is flagged when compiled on some machines.

**Comment by BDisp** [comment]
> 
> 
> > @paolo-projects and @mkitchingh, I use VS 2019 for developing with the integrated Python and realized that the compiled exe not generate any virus warnings. However, I did not want to advance because the laurels are for you both and I was waiting for @paolo-projects release and merge with his fork :)
> 
> Didn't know VS2019 compiles python code... wow! There's some spare laurels for you too! You can also create a pull request with your compiled fork I'll merge it

Thanks @paolo-projects I'm in doubt if the pull request is done on your fork or in DrDonk?

**Comment by alexnt85** [comment]
@paolo-projects I assume same problem with mojave...???

**Comment by maxcarna** [comment]
Hi, just providing some feedback:
I followed this tutorial https://techsviewer.com/install-macos-mojave-vmware-windows/
I got the package's problem with DrDonk project, so I ended up here. I downloaded paolo-projects version (clone download from master). Everything seems to be fine on the first attempt, I'm finishing step 8 from the tutorial. 
My setup:
- Jingsha x79 dual xeon E5-2650 v2 with ADATA XPG x11 M.2 SSD
- Windows 10 1903 18362.418
- VMWare Player 15
- MAC OS 10.14 iso from https://isoriver.com
Thank you very much for this fix.

**Comment by BDisp** [comment]
@maxcarna you can also download Catalina. See how at https://techsviewer.com/how-to-install-macos-10-15-catalina-on-vmware-on-windows-pc/ and in step 8 do not switch to Windows 10. Check my comments. John rejected my comment there where I say to not follow that step which misleads many with the distress of not being able to install

**Comment by maxcarna** [comment]
> @maxcarna you can also download Catalina. See how at https://techsviewer.com/how-to-install-macos-10-15-catalina-on-vmware-on-windows-pc/ and in step 8 do not switch to Windows 10. Check my comments. John rejected my comment there where I say to not follow that step which misleads many with the distress of not being able to install

I believe I didn't switch, but everything is working now. I have a website and just wanted to try on Mac. Thank you

**Pull request merged**
