### PR TITLE
updated vmwaretools link, binarys and sample vmx file

### PR DESCRIPTION
**Pull request by flyinghuman**
i updated the vmware tools path and also the binarys. works for 15.5 if you manually create the vmx file (MacOS is not selectable in New Virtual Machine Wizard but if you use a existing MacOS vmx File you will be able to edit and boot it.) i attached a sample vmx file for that.

### CODE REVIEW

**Comment by kocane** [comment]
This is some divine intervention shit, I was in dire need to have a MacOS VM to test some software and literally 6 minutes after seeing the patch fails with downloading the Tools ZIP, I spot your fork. Thanks!

**Comment by mkitchingh** [comment]
@flyinghuman  Can you help me understand why you would want to make this change?
```
in win-install.cmd 
-gettools.exe
+python gettools.py
```
I believe the point of the compiled versions is so Windows machines don't need to have Python installed. The Pyinstaller compiled versions of the file work well. Also, there is a patch floating around that does work so MAc is an option in the dropdown menu. 
https://www.insanelymac.com/forum/topic/335757-macos-unlocker-v30-for-vmware-workstation/?page=3&tab=comments#comment-2691430
I assume Donk will release an official update.

**Comment by kyle-tw** [comment]
It is nice to get the last darwin.iso file,But when my macOS update VMWare Tools then my macOS display resolution always on 1024*768 can not change. When I copy my backup VM files and restore macOS do not update VMWare Tools, the macOS can change display resolution normal. My macOS version is OS X 10.11.

**Comment by BDisp** [comment]
@kyle-tw you can use the /Library/Application Support/VMware Tools/vmware-resolutionSet. However I recommended update to Mojave especially if you are using the Xcode.

**Comment by kyle-tw** [comment]
> @kyle-tw you can use the /Library/Application Support/VMware Tools/vmware-resolutionSet. However I recommended update to Mojave especially if you are using the Xcode.
Thank you for your reply. I had update VMware Tools again. When I type this command on Terminal then it show "Unable to find the service". I think this  new version for VMware Tools is not support macOS Sierra. Then I install old version for VMware Tools ,it works again. Thank you.

**Comment by flyinghuman** [comment]
hey, please use the paolo-projects version. it works fine and also has updated tools link in. i will close this PR now.

**Pull request closed without merging**
