### PR TITLE
Docs: Convert readme to markdown format

### PR DESCRIPTION
**Pull request by Minimalistic**
Adjusted formatting, added backticks for code and command formatting.

### CODE REVIEW

**Comment by abdullaherk** [comment]
Not work for vmware 14

**Comment by rcsavage** [comment]
Yes, I can confirm this is not working on VMWare Workstation Pro 14.0.   I can help provide one of my test stations if you need access.   Or tell me what to look for to modify in your code and I will work on it and submit a PR.

**Comment by romash1408** [comment]
@Minimalistic, you need to rename "readme.txt" to "readme.md". Github doesn't see your markdown format in txt file :D
default

**Comment by Minimalistic** [comment]
... Better late than never?

**Comment by DrDonk** [comment]
I will look into adding the Markdown version but also require text only for Insanelymac. I will close this request as the file has been re-written for V3 and needs to be converted to markdown again.

**Pull request closed without merging**
