### PR TITLE
added support for ESXi 6.7.0

### PR DESCRIPTION
**Pull request by ANGELMARS**
ESXi 6.7.0 has installed successfully

### CODE REVIEW

**Comment by LordVeovis** [comment]
Hi @ANGELMARS 
I know that some adventurers have use this patch on their esxi 6.7 with some success, I doubt this merge will be accepted as the last commit unfortunately, removed all support for ESXi as the patch lead to unstable esxi under certain circumstances.

**Comment by mehrshad000** [comment]
unlocker not work on wmvare 14
VMware Unlocker 2.1.1
========================
(c) Dave Parsons 2011-17
ERROR: The system was unable to find the specified registry key or value.
VMware is installed at:
Stopping VMware services...
Backing up files...
File not found - vmware-vmx.exe
0 File(s) copied
File not found - vmware-vmx-debug.exe
0 File(s) copied
File not found - vmware-vmx-stats.exe
0 File(s) copied
File not found - vmwarebase.dll
0 File(s) copied
Patching...
Traceback (most recent call last):
  File "unlocker.py", line 432, in <module>

  File "unlocker.py", line 397, in main
    vmx_debug = joinpath(vmx_path, 'vmware-vmx-debug.exe')
WindowsError: [Error 2] The system cannot find the file specified
[12544] Failed to execute script unlocker
Getting VMware Tools...

**Comment by zjcnew** [comment]
Whether to support macOS High Sierra?

**Comment by LordVeovis** [comment]
@zjcnew that's the spirit. The support for esxi is to disable the software lock that forbid esxi to run a macOS vm (whatever the version) on a non apple hardware.

**Comment by LordVeovis** [comment]
@megapearl  did you read https://www.insanelymac.com/forum/topic/328285-macos-unlocker-21-for-vmware-workstation-111214-player-71214-fusion-7810/ ?

**Comment by zjcnew** [comment]
@LordVeovis I mean whether to support unlocking VMware esxi or workstation virtual machine to install macOS High Sierra.

**Comment by LazaRocks** [comment]
@LodVeovis and @zjcnew:  unlocker 3.0.0 with support for ESXi 6.7 is out! 
Check [https://github.com/DrDonk/unlocker/commit/1073f82f1f32c71d0f08a8c0924b833f2fe57017](url)

I just wonder if one can use unlocker 3.0.0 on an older versions of ESXi, specifically version 6.0 Update 3
 
I hope DrDonk reads this thread and answer it. BTW Congratulations with your new situation!

**Comment by DrDonk** [comment]
There is a new ESXi unlocker. https://github.com/DrDonk/esxi-unlocker So closing this. Thanks.

**Pull request closed without merging**
