### PR TITLE
Fix download url for darwinPre15 VMware Tools

### PR DESCRIPTION
**Pull request by shelaf**
Downloaded darwinPre15.iso is the as same as darwin.iso.
Therefore, VMware Tools can not install below OS X 10.10.

### CODE REVIEW

**Comment by jerson** [comment]
Hello everyone, check the url
http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/
you will see that now the last result is not the same as the last available version, it may be necessary to update this part

https://github.com/DrDonk/unlocker/blob/b036c40ab1922d9abf4f7d68e34f1eca3b4dc2ad/gettools.py#L88

https://github.com/DrDonk/unlocker/blob/b036c40ab1922d9abf4f7d68e34f1eca3b4dc2ad/gettools.py#L96

**Comment by shelaf** [comment]
I agree with you.
But, the url are for VMware Fusion, not for VMware Player/Workstation.
So, I have no idea which version is best.

**Comment by jerson** [comment]
hi @shelaf latest version is http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/10.1.1/ acording
https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_fusion/10_0

**Comment by shelaf** [comment]
@jerson I understand what you mean. I had a misunderstanding.
`parser.HTMLDATA` is sorted in ascending order of version numbers. So, last result is latest version.
https://github.com/DrDonk/unlocker/blob/b036c40ab1922d9abf4f7d68e34f1eca3b4dc2ad/gettools.py#L56

**Comment by jerson** [comment]
@shelaf you're right, it was my mistake, it seems that everything is fine, I did not read that line, I'm sorry :)

**Comment by DrDonk** [comment]
Looks like this does need investigating.

**Comment by DrDonk** [comment]
This was fixed in 2.1.0. Thanks

**Comment by shelaf** [comment]
This is not fixed yet.

https://github.com/DrDonk/unlocker/blob/master/gettools.py#L129
It is need to extact darwinPre15.zip instead of darwin.zip
```
tar = tarfile.open(convertpath(dest + '/tools/com.vmware.fusion.tools.darwinPre15.zip.tar'), 'r')
tar.extract('com.vmware.fusion.tools.darwin.zip', path=convertpath(dest + '/tools/'))
```

**Pull request closed without merging**
