### PR TITLE
At the request of @paolo-projects

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by Jan-E** [comment]
@BDisp @paolo-projects @DrDonk 
This did the job! One remark: unlocker.exe was not trusted (yet?) by Windows Security of Windows 10, so I had to add a scan exclusion to do perform the patch.

This PR also fetched the latest darwin.iso.

Thanks

selectos

**Comment by BDisp** [comment]
@ Jan-E I think this is unnecessary because the location of the ISO tools have only been changed from version 15.5.0, so if not found in package should only be searched in the core. In fact the code to find in older versions will never be executed because it will even be found in the core. So I think this logic is useless.

**Comment by fhw** [comment]
@BDisp thank you! i unlock vm 15.5 successful!

**Comment by mkitchingh** [comment]
So, do we thing the @DrDonk or @paolo-projects version is going to be the official going forward? Will they split, or is someone going to merge the 2?

**Comment by BDisp** [comment]
> 
> 
> So, do we thing the @DrDonk or @paolo-projects version is going to be the official going forward? Will they split, or is someone going to merge the 2?

DrDonk/Releases is up to date but DrDonk needed to merged into his repository. Looks like he's  already dealing with it. In my opinion the confirmations of @paolo-projects and mine exe's are enough, but of course DrDonk will compile again and we would get an final official version. For me is finished.

**Comment by mmalewski** [comment]
When will this get fixed/updated?  I'm still having the same exact problem with the DrDonk version, and I downloaded the very latest master, and it's not working.  It seems that "gettools.py" has not been properly updated in the DrDonks version.

I had to manually edit the "gettools.py" file and manually change the /packages/ folder and remove it, and change it to /core/ because there is no longer any packages folders on the VMware website.  The packages folders have all been removed, and it seems that the "gettools.py" script has not been updated to reflect that.

So I did change the "gettools.py" script to "/core/" instead of "/packages/"

It was able to download the VMware tools/package from the VMware website after I made those changes manually, but these changes should probably be updated in the DrDonk version, and the "gettools.py" script needs to be fixed and the "/packages/" should be removed and replaced with "/core". 

There is no point in having a broken GetTools.py script that points to folder/directories that don't exist on the VMware website anymore, and the tools are unable to download.  So it would be good to please get this fixed/updated.

Hopefully someone can update the "gettools.py" script and merge this into the DrDonk repository, so that we actually have an updated and working version/repository.  The current version is broken, and still doesn't work.  I had to manually edit the "gettools.py" script, and remove all the "/packages/" and change them to "/core/" in order for gettools.py to actually work.

Hopefully this gets fixed soon!

**Comment by BDisp** [comment]
There is a fix at https://github.com/paolo-projects/unlocker/releases/tag/3.0.3

**Pull request closed without merging**
